---
spring:
  neo4j:
    uri: bolt://localhost:7689
    authentication:
      username: neo4j
      password: asdzxc1122..
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
server:
  port: 8081

  application:
    name: 'Orchestration Api'
    description: 'Orchestration Api Documentation'

swagger:
  host:
    url: localhost:8081
    protocol: http
  contact:
    name: GraphBackend
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: '@version@'


logging:
  level:
    org:
      springframework:
        data:
          neo4j=DEBUG:



feign:
  httpclient:
    connection-timeout: 15000
  client:
    config:
      mpi-api:
        url: http://localhost:8080
  hystrix:
    enabled: false