---
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  application:
    name: 'Orchestration Api'
    description: 'Orchestration Api Documentation'

swagger:
  host:
    url: localhost:8080
    protocol: http
  contact:
    name: Xox
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: '@version@'

mongodb:
  connection-string: 'mongodb://178.62.241.217:27017/test'
  database: 'football'
  collection:
    player: 'player'
    team: 'team'
    league: 'league'
    player-team: 'player_team'
    team-matching: 'team_matching'
